src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IEmployeRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IOfficeRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IPaymentRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IEmployeeService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IOfficeService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IPaymentService.java
agregando cambios provisionales
=> Req9 repository

src/main/java/ar/edu/unju/fi/tpfinal/models/OrderDetail.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Product.java, src/main/java/ar/edu/unju/fi/tpfinal/models/ProductLine.java
se creo la clase Product, ProductLine y orderDetail
=> clases creadas en el paquete models

src/main/java/ar/edu/unju/fi/tpfinal/models/Customers.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Orders.java
Se crearon los modelos Customers y Orders.
=> Req2 Modelos Customers y Orders.

src/main/java/ar/edu/unju/fi/tpfinal/models/OrderDetail.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Product.java, src/main/java/ar/edu/unju/fi/tpfinal/models/ProductLine.java
aun no puedo relacionar la tabla order detail con su llaves primarias
compuestas
=> Las tablas se conectan a la bd

src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/ICustomersRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IOrdersRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/ICustomersService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IOrdersService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/CustomersServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/OrdersServiceImpMySQL.java
Se crearon los repositorios, los services y los implementadores de los modelos Customers y Orders.
=> Req11 repositoy service imp customers orders

src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IOrderDetailRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IProductLineRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IProductRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IOrderDetailService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IProductLineService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IProductService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/OrderDetailServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/ProductLineServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/ProductServiceImpMySQL.java
Product ProductLine y OrderDetail
=> se creo repository service e implementacion

src/main/java/ar/edu/unju/fi/tpfinal/models/Usuario.java, src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IUsuarioRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IUsuarioService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/OrderDetailServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/ProductLineServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/ProductServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/UsuarioServiceImp.java
se agrego @service  en las implementaciones Product productLines y
orderDetall
=> Se creo repository service e impl de Usuario

src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Employee.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Usuario.java, src/main/resources/templates/new-employee.html
se modifico clase Employe para poder crear usuario en el template
se creo controller solo para la ruta empleado nuevo(/employee/new/)
=> Se creo Template Employe

src/main/java/ar/edu/unju/fi/tpfinal/controller/ProductLineController.java, src/main/java/ar/edu/unju/fi/tpfinal/models/ProductLine.java, src/main/resources/templates/new-productLine.html
se creo controller para mostrar pagina
se modifico clase ProductLine se agrego @lop para la imagen y en column
se agrego descripcion da la columna
=> Se creo template new-produtLine

src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java
Se Creo el Controller de la clase Employees
=> Agregando controller employee

src/main/resources/templates/new-customer.html
Se creo el template para el formulario de alta de Customers.
=> Template alta-customer

src/main/resources/templates/all-productsLine.html
Se creo el Template donde se muestra la tabla de ProductLine.
=> Template all-productsLine

hs_err_pid9000.log, src/main/java/ar/edu/unju/fi/tpfinal/models/OrderDetail.java, src/main/java/ar/edu/unju/fi/tpfinal/models/OrderDetailId.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Orders.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Product.java, src/main/java/ar/edu/unju/fi/tpfinal/models/ProductLine.java, src/main/java/ar/edu/unju/fi/tpfinal/reposiroty/IOrderDetailRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IOrderDetailService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/OrderDetailServiceImpMySQL.java, src/test/java/ar/edu/unju/fi/tpfinal/OrderDetailTest.java
aun no puedo hacer que guarde en el tes
=> Se hizo mapeo en orderDetail

src/main/java/ar/edu/unju/fi/tpfinal/controller/OrderController.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/OrdersServiceImpMySQL.java, src/main/resources/templates/new-order.html
la pagina new-order se muestra bien
se creo los metodos para editar guardar y eliminar a demas de mostrar
todos y visualizar la pagina new order
=> se creo OrderControler

src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java, src/main/resources/templates/new-employee.html
modificaciones al controller de employee.
=> controller employee

src/main/resources/templates/all-order.html
Se creo el Template de all-order para mostrar la lista de orders.
=> Template all order

src/main/java/ar/edu/unju/fi/tpfinal/controller/PaymentsController.java
Se creo el Controller para Payments con los módulos necesarios como guardar, listar, editar y eliminar.
=> Controller payments

src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java
Se arreglaron algunos bugs sobre el controller.
=> Arreglos al Controller Employee.

src/main/resources/templates/new-product.html
Se creo el Template para el ingreso de nuevos productos- template / new-product.
=> Template new product

src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java
Pequeños arreglos al controller.
=> Arrgelos al controller.

src/main/resources/templates/new-orderdetails.html
Se creo un previo Template new-orderDetails.
=> Template new order details

src/main/java/ar/edu/unju/fi/tpfinal/controller/CustomerController.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/ProductController.java, src/main/resources/templates/all-customer.html, src/main/resources/templates/new-customer.html, src/main/resources/templates/new-employee.html, src/main/resources/templates/new-order.html, src/main/resources/templates/new-orderdetails.html, src/main/resources/templates/new-product.html, src/main/resources/templates/new-productLine.html, src/main/resources/templates/nuevo-office.html
esta funcionando el controler correctamente
se modifico nombre de los botones   new por save
=> Se creo CustomerControler

src/main/resources/templates/all-payments.html
Se creo el template all-payments donde se muestra la lista de todos los payments.
=> Template all payment

pom.xml, src/main/java/ar/edu/unju/fi/tpfinal/controller/CustomerController.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/OrderController.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Customers.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Orders.java, src/main/resources/templates/new-customer.html, src/main/resources/templates/new-order.html
Se agregaron las notaciones necesarias para la validacion al ingreso de Customers y Orders.
=> Validacion customer order

src/main/java/ar/edu/unju/fi/tpfinal/models/Customers.java
Se cambio el tipo del atributo phone.
=> Pequeños cambios en el modelo Customers.

src/main/java/ar/edu/unju/fi/tpfinal/controller/OrderDetailController.java, src/main/resources/templates/all-orderDetail.html, src/main/resources/templates/new-orderdetails.html
=> Se creo OrderDetailController

src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java, src/main/resources/templates/all-employee-account.html, src/main/resources/templates/layout/header-employee.html
Se creo una tabla para mostar los employee con los datos de usuario.
=> Template all-employee-account.

src/main/java/ar/edu/unju/fi/tpfinal/controller/PaymentsController.java, src/main/resources/templates/new-payment.html
la paginalevanta bien
controlar los metodos de controller
=> Se creo template new-payment

src/main/java/ar/edu/unju/fi/tpfinal/controller/LoginController.java, src/main/resources/templates/login.html
el template login lebanta bien
=> Se creo template login

src/main/java/ar/edu/unju/fi/tpfinal/controller/CustomerController.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/OrderDetailController.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/ProductController.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/ProductLineController.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Employee.java, src/main/java/ar/edu/unju/fi/tpfinal/models/OrderDetail.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Product.java, src/main/java/ar/edu/unju/fi/tpfinal/models/ProductLine.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Usuario.java, src/main/resources/templates/new-employee.html, src/main/resources/templates/new-orderdetails.html, src/main/resources/templates/new-product.html, src/main/resources/templates/new-productLine.html
Se agragaron validaciones products, productsLine y orderDetalis, ademas se modificaron los controllers y templates para las validaciones.
=> Validaciones

src/main/java/ar/edu/unju/fi/tpfinal/models/Orders.java
se hizo la documentacion para la clase orders
=> Documentacion Orders

src/main/java/ar/edu/unju/fi/tpfinal/controller/CustomerController.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/EmployeeControlles.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/OfficeController.java, src/main/java/ar/edu/unju/fi/tpfinal/controller/OrderDetailController.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Customers.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Employee.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Office.java, src/main/java/ar/edu/unju/fi/tpfinal/models/OrderDetail.java, src/main/java/ar/edu/unju/fi/tpfinal/models/OrderDetailId.java
Documentacion a Modelos y Controllers
=> Documentacion

src/main/java/ar/edu/unju/fi/tpfinal/repository/ICustomersRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/repository/IEmployeRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/repository/IOfficeRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/repository/IOrderDetailRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/ICustomersService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IEmployeeService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IOfficeService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IOrderDetailService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/CustomersServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/EmployeeServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/OfficeServiceImpMySQL.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/OrderDetailServiceImpMySQL.java
=> Documentación

src/main/java/ar/edu/unju/fi/tpfinal/controller/OrderController.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Orders.java, src/main/java/ar/edu/unju/fi/tpfinal/repository/IOrdersRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IOrdersService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/OrdersServiceImpMySQL.java
se termino de documentar repository service service imp
=> Documentacion de Orders

src/main/java/ar/edu/unju/fi/tpfinal/controller/PaymentsController.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Payment.java, src/main/java/ar/edu/unju/fi/tpfinal/repository/IPaymentRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IPaymentService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/PaymentServiceImpMySQL.java
se agrego documentacion en controler repository y services
=> documentacion Payment

src/main/java/ar/edu/unju/fi/tpfinal/controller/ProductController.java, src/main/java/ar/edu/unju/fi/tpfinal/models/Product.java, src/main/java/ar/edu/unju/fi/tpfinal/repository/IProductRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IProductService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/ProductServiceImpMySQL.java
se documento controller repository service imp y service
=> documentacion Product

src/main/java/ar/edu/unju/fi/tpfinal/controller/ProductLineController.java, src/main/java/ar/edu/unju/fi/tpfinal/models/ProductLine.java, src/main/java/ar/edu/unju/fi/tpfinal/repository/IProductLineRepository.java, src/main/java/ar/edu/unju/fi/tpfinal/service/IProductLineService.java, src/main/java/ar/edu/unju/fi/tpfinal/service/imp/ProductLineServiceImpMySQL.java
se agrego documentacion en controller models repository
service y service imp
=> Documentacion ProductLine
